### Create new article
POST  http://localhost:3010/articles
Content-Type: application/json

{
    "title": "TypeScripy",
    "content": "Hello, Welcome to...",
    "userId": 1
}

### Find all articles
GET  http://localhost:3010/articles
Content-Type: application/json

### Find one article
GET  http://localhost:3010/articles/1
Content-Type: application/json

### Update one article
PUT   http://localhost:3010/articles/1
Content-Type: application/json

{
    "title": "TypeScripT",
    "content": "Hello, Welcome to...",
    "userId": 1
}

### Delete one article
DELETE    http://localhost:3010/articles/2
Content-Type: application/json